import os, datetime, pathlib, json

today = datetime.datetime.now().strftime("%Y-%m-%d")
out_dir = pathlib.Path("docs/daily") / today[:7]
out_dir.mkdir(parents=True, exist_ok=True)
out_path = out_dir / f"{today}_Shibi_Daily_Log.md"

if not out_path.exists():
    content = f"""# 志火 Daily Log — {today}

## 🌤 今日のテーマ（静／動）
- 静：…
- 動：…

## 🔥 志火メモ
- …

## 🤝 志耀（つながり／共感）
- …

## ✅ アクション（3つまで）
- [ ] …
- [ ] …
- [ ] …

---
*Generated by GAN Project Auto Generator.*
"""
    out_path.write_text(content, encoding="utf-8")
    print(f"[OK] created: {out_path}")
else:
    print(f"[SKIP] already exists: {out_path}")

print(json.dumps({"created": str(out_path)}))
